services:
  #Database
  ihs_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3320:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: ihs_db
  #Web
  ihs_wp:
    depends_on:
      - ihs_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8097:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: ihs_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: ihs_
    container_name: ihs_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  ihs_myadmin:
    image: phpmyadmin:latest
    container_name: ihs_myadmin
    restart: "no"
    ports:
      - 5017:80
    environment:
      PMA_HOST: ihs_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - ihs_db
volumes:
  db_data:
  wp-content:
